package ec.edu.ups.practica.siete.quitokaren.penasofia.vista.cantante;


import ec.edu.ups.practica.siete.quitokaren.penasofia.controlador.ControladorCantante;
import ec.edu.ups.practica.siete.quitokaren.penasofia.modelo.Cantante;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

import javax.swing.JOptionPane;
import javax.swing.border.Border;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author PhD. Gabriel A. León Paredes
 */
public class VentanaActualizarCantante extends javax.swing.JInternalFrame {

    private ControladorCantante controladorCantante;
    private ResourceBundle mensajes;
    /**
     * Creates new form VentanaActualizarPersona
     */
    public VentanaActualizarCantante(ControladorCantante controladorCantante) {
        initComponents();
        this.controladorCantante = controladorCantante;
    }
    
    
        public void cambiarIdioma(Locale localizacion) {
        mensajes = ResourceBundle.getBundle("mensajes.mensaje", localizacion);
        lblNombre.setText(mensajes.getString("lbl.nombre"));
        lblApellido.setText(mensajes.getString("lbl.apellido"));
        lblCodigo.setText(mensajes.getString("lbl.codigo"));
        lblEdad.setText(mensajes.getString("lbl.edad"));
        lblSalarioCant.setText(mensajes.getString("lbl.salario"));
        lblNacionalidadCant.setText(mensajes.getString("lbl.nacionalidad"));
        lblNombreArtisticoCant.setText(mensajes.getString("lbl.nombreArtistico"));
        lblGeneroMusicalCant.setText(mensajes.getString("lbl.generoMusical"));
        lblNSencillosCant.setText(mensajes.getString("lbl.nSencillos"));
        lblNConciertosCant.setText(mensajes.getString("lbl.nConciertos"));
        lblNGirasCant.setText(mensajes.getString("lbl.nGiras"));
        btnBuscar.setText(mensajes.getString("menu.item.buscar"));
        btnAceptar.setText(mensajes.getString("btn.aceptar"));
        btnCancelar.setText(mensajes.getString("btn.Cancelar"));
        String borderTitle = mensajes.getString("jpanel.actCant");
        Border border = BorderFactory.createTitledBorder(borderTitle);
        jPanel1.setBorder(border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtGeneroMusical = new javax.swing.JTextField();
        lblSalarioCant = new java.awt.Label();
        txtNSencillos = new javax.swing.JTextField();
        lblNombreArtisticoCant = new java.awt.Label();
        txtSalario = new javax.swing.JTextField();
        lblGeneroMusicalCant = new java.awt.Label();
        txtNombreArtistico = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        lblCodigo = new java.awt.Label();
        txtNConciertos = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new java.awt.Label();
        txtNGiras = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        lblApellido = new java.awt.Label();
        btnCancelar = new javax.swing.JButton();
        lblNConciertosCant = new java.awt.Label();
        btnBuscar = new javax.swing.JButton();
        lblNGirasCant = new java.awt.Label();
        lblNSencillosCant = new java.awt.Label();
        txtEdad = new javax.swing.JTextField();
        lblEdad = new java.awt.Label();
        lblNacionalidadCant = new java.awt.Label();
        btnAceptar = new javax.swing.JButton();
        cbxNacionalidad = new javax.swing.JComboBox<>();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(236, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Actualizar Persona", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(860, 370));

        txtGeneroMusical.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        txtGeneroMusical.setForeground(new java.awt.Color(51, 102, 255));
        txtGeneroMusical.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtGeneroMusical.setToolTipText("");
        txtGeneroMusical.setEnabled(false);
        txtGeneroMusical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneroMusicalActionPerformed(evt);
            }
        });

        lblSalarioCant.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblSalarioCant.setText("Salario");

        txtNSencillos.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        txtNSencillos.setForeground(new java.awt.Color(51, 102, 255));
        txtNSencillos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNSencillos.setToolTipText("");
        txtNSencillos.setEnabled(false);
        txtNSencillos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNSencillosActionPerformed(evt);
            }
        });

        lblNombreArtisticoCant.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblNombreArtisticoCant.setText("Nombre Artistico");

        txtSalario.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        txtSalario.setForeground(new java.awt.Color(51, 102, 255));
        txtSalario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSalario.setToolTipText("");
        txtSalario.setEnabled(false);

        lblGeneroMusicalCant.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblGeneroMusicalCant.setText("Genero Musical");

        txtNombreArtistico.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        txtNombreArtistico.setForeground(new java.awt.Color(51, 102, 255));
        txtNombreArtistico.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombreArtistico.setToolTipText("");
        txtNombreArtistico.setEnabled(false);

        txtCodigo.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(51, 102, 255));
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCodigo.setToolTipText("Ingrese el codigo del cantante");

        lblCodigo.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblCodigo.setText("Codigo");

        txtNConciertos.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        txtNConciertos.setForeground(new java.awt.Color(51, 102, 255));
        txtNConciertos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNConciertos.setToolTipText("");
        txtNConciertos.setEnabled(false);

        txtNombre.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(51, 102, 255));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombre.setToolTipText("");
        txtNombre.setEnabled(false);

        lblNombre.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblNombre.setText("Nombre");

        txtNGiras.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        txtNGiras.setForeground(new java.awt.Color(51, 102, 255));
        txtNGiras.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNGiras.setToolTipText("");
        txtNGiras.setEnabled(false);

        txtApellido.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(51, 102, 255));
        txtApellido.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtApellido.setToolTipText("");
        txtApellido.setEnabled(false);

        lblApellido.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblApellido.setText("Apellido");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cancel.24.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblNConciertosCant.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblNConciertosCant.setText("Numero de Conciertos");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Find-User.24.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblNGirasCant.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblNGirasCant.setText("Numero de Giras");

        lblNSencillosCant.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblNSencillosCant.setText("Numero de Sencillos");

        txtEdad.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        txtEdad.setForeground(new java.awt.Color(51, 102, 255));
        txtEdad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEdad.setToolTipText("");
        txtEdad.setEnabled(false);

        lblEdad.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblEdad.setText("Edad");

        lblNacionalidadCant.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblNacionalidadCant.setText("Nacionalidad");

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Edit-User.24.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        cbxNacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccione un pais---" }));
        cbxNacionalidad.setEnabled(false);
        cbxNacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNacionalidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSalarioCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSalario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGeneroMusicalCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreArtisticoCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombreArtistico, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGeneroMusical, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNacionalidadCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxNacionalidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnBuscar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNSencillosCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNGirasCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNConciertosCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNConciertos, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNSencillos, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNGiras, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 160, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addGap(317, 317, 317))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBuscar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNacionalidadCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNSencillos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNSencillosCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNConciertosCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNConciertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNGirasCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNGiras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSalarioCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreArtisticoCant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreArtistico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGeneroMusicalCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGeneroMusical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        this.limpiarCampos();
        this.cambiarEstadoCampos(false);
    }//GEN-LAST:event_formInternalFrameClosing

    private void txtGeneroMusicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroMusicalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroMusicalActionPerformed

    private void txtNSencillosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNSencillosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNSencillosActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.limpiarCampos();
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String codigoS = txtCodigo.getText();
        int codigo = Integer.parseInt(codigoS);
        Cantante cantan = controladorCantante.buscar(codigo);
        if (cantan != null) {
            txtNombre.setText(cantan.getNombre());
            txtApellido.setText(cantan.getApellido());
            txtEdad.setText(String.valueOf(cantan.getEdad()));
            cbxNacionalidad.setSelectedItem(cantan.getNacionalidad());
            txtSalario.setText(String.valueOf(cantan.calcularSalario()));
            txtNombreArtistico.setText(cantan.getNombreArtistico());
            txtGeneroMusical.setText(cantan.getGeneroMusical());
            txtNSencillos.setText(String.valueOf(cantan.getNumeroDeSencillos()));
            txtNConciertos.setText(String.valueOf(cantan.getNumeroDeConciertos()));
            txtNGiras.setText(String.valueOf(cantan.getNumeroDeGiras()));
            this.cambiarEstadoCampos(true);
            txtCodigo.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "La persona con codigo " + codigo + " no ha sido encontrada!");
        }  
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String codigoS = txtCodigo.getText();
        int codigo = Integer.parseInt(codigoS);
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String edadS = txtEdad.getText();
        int edad = Integer.parseInt(edadS);
        String nacionalidad = (String) cbxNacionalidad.getSelectedItem();
        String salarioS = txtSalario.getText();
        double salario = Double.parseDouble(salarioS);
        String nombreArtistico = txtNombreArtistico.getText();
        String generoMusical = txtGeneroMusical.getText();
        String nSencillos = txtNSencillos.getText();
        int numeroDeSencillos = Integer.parseInt(nSencillos);
        String nConciertos = txtNConciertos.getText();
        int numeroDeConciertos = Integer.parseInt(nConciertos);
        String nGiras = txtNGiras.getText();
        int numeroDeGiras = Integer.parseInt(nGiras);
        
        Cantante c = new Cantante(nombreArtistico, generoMusical, numeroDeSencillos, numeroDeConciertos, numeroDeGiras, codigo, nombre, apellido, edad, nacionalidad, salario);
        if (controladorCantante.actualizar(c)){
            JOptionPane.showMessageDialog(this, "El cantante ha sido actualizado exitosamente! :)");
            this.limpiarCampos();
            this.cambiarEstadoCampos(false);
        }else{
            JOptionPane.showMessageDialog(this, "El cantante no ha sido actualizada! :(");
        
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void cbxNacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNacionalidadActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbxNacionalidadActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
         String rutaArchivo = "src/main/resources/paises.csv";
        // Cargar datos del archivo Excel en el JComboBox
        cargarDatosExcel(rutaArchivo, cbxNacionalidad, Locale.getDefault().getLanguage());
    }//GEN-LAST:event_formInternalFrameActivated

    private void cargarDatosExcel(String rutaArchivo, JComboBox<String> comboBox, String idioma) {
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();

        try {
            BufferedReader br = new BufferedReader(new FileReader(rutaArchivo));
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] valores = linea.replaceAll("\"", "").split(",");
                if (valores.length > 0) {
                    String valor;
                    if (idioma.equals("en")) {
                        valor = valores[0]; // Columna para idioma ingles
                    } else if (idioma.equals("es")) {
                        valor = valores[1]; // Columna para idioma español
                    } else {
                        valor = valores[2]; // Columna para idioma frances
                    }
                    comboBoxModel.addElement(valor);
                }
            }
            br.close();
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("no se puedo");
        }
        comboBox.setModel(comboBoxModel);
    }
    private void limpiarCampos() {
        this.txtCodigo.setText("");
        this.txtNombre.setText("");
        this.txtApellido.setText("");
        this.txtEdad.setText("");
        this.cbxNacionalidad.setSelectedIndex(0);
        this.txtSalario.setText("");
        this.txtNombreArtistico.setText("");
        this.txtGeneroMusical.setText("");
        this.txtNSencillos.setText("");
        this.txtNConciertos.setText("");
        this.txtNGiras.setText("");
    }

    private void cambiarEstadoCampos(boolean estado) {
        this.txtCodigo.setEnabled(!estado);
        this.txtNombre.setEnabled(estado);
        this.txtApellido.setEnabled(estado);
        this.txtEdad.setEnabled(estado);
        this.cbxNacionalidad.setEnabled(estado);
        this.txtSalario.setEnabled(estado);
        this.txtNombreArtistico.setEnabled(estado);
        this.txtGeneroMusical.setEnabled(estado);
        this.txtNSencillos.setEnabled(estado);
        this.txtNConciertos.setEnabled(estado);
        this.txtNGiras.setEnabled(estado);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbxNacionalidad;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label lblApellido;
    private java.awt.Label lblCodigo;
    private java.awt.Label lblEdad;
    private java.awt.Label lblGeneroMusicalCant;
    private java.awt.Label lblNConciertosCant;
    private java.awt.Label lblNGirasCant;
    private java.awt.Label lblNSencillosCant;
    private java.awt.Label lblNacionalidadCant;
    private java.awt.Label lblNombre;
    private java.awt.Label lblNombreArtisticoCant;
    private java.awt.Label lblSalarioCant;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtGeneroMusical;
    private javax.swing.JTextField txtNConciertos;
    private javax.swing.JTextField txtNGiras;
    private javax.swing.JTextField txtNSencillos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreArtistico;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
